require 'java'

module Embulk::Java
  java_import 'org.embulk.time.Timestamp'
  java_import 'org.embulk.time.TimestampFormatter'
  java_import 'org.embulk.time.TimestampParser'
  java_import 'org.embulk.time.TimestampParseException'

  java_import 'org.embulk.buffer.Buffer'
  java_import 'org.embulk.buffer.BufferAllocator'

  java_import 'org.embulk.channel.BufferChannel'
  java_import 'org.embulk.channel.BufferInput'
  java_import 'org.embulk.channel.BufferOutput'
  java_import 'org.embulk.channel.ChannelAsynchronousCloseException'
  java_import 'org.embulk.channel.ChannelInterruptedException'
  java_import 'org.embulk.channel.DataChannel'
  java_import 'org.embulk.channel.FileBufferChannel'
  java_import 'org.embulk.channel.FileBufferInput'
  java_import 'org.embulk.channel.FileBufferOutput'
  java_import 'org.embulk.channel.PageChannel'
  java_import 'org.embulk.channel.PageInput'
  java_import 'org.embulk.channel.PageOutput'

  #java_import 'org.embulk.config.Config'  # namespace conflicts
  java_import 'org.embulk.config.ConfigDefault'
  java_import 'org.embulk.config.ConfigException'
  java_import 'org.embulk.config.ConfigSource'
  java_import 'org.embulk.config.DataSource'
  java_import 'org.embulk.config.ModelManager'
  java_import 'org.embulk.config.NextConfig'
  java_import 'org.embulk.config.Report'
  java_import 'org.embulk.config.Task'
  java_import 'org.embulk.config.TaskSource'
  java_import 'org.embulk.config.TaskValidationException'

  java_import 'org.embulk.record.Column'
  java_import 'org.embulk.record.ColumnConfig'
  java_import 'org.embulk.record.DoubleType'
  java_import 'org.embulk.record.LongType'
  java_import 'org.embulk.record.Page'
  java_import 'org.embulk.record.PageAllocator'
  java_import 'org.embulk.record.Pages'
  java_import 'org.embulk.record.PageBuilder'
  java_import 'org.embulk.record.PageReader'
  java_import 'org.embulk.record.RecordWriter'
  java_import 'org.embulk.record.RecordReader'
  java_import 'org.embulk.record.Schema'
  java_import 'org.embulk.record.SchemaConfig'
  java_import 'org.embulk.record.StringType'
  java_import 'org.embulk.record.Type'
  java_import 'org.embulk.record.TypeManager'

  java_import 'org.embulk.spi.BasicFormatterPlugin'
  java_import 'org.embulk.spi.BasicParserPlugin'
  java_import 'org.embulk.spi.GuessPlugin'
  java_import 'org.embulk.spi.FileDecoderPlugin'
  java_import 'org.embulk.spi.FileEncoderPlugin'
  java_import 'org.embulk.spi.FileInputPlugin'
  java_import 'org.embulk.spi.FileOutputPlugin'
  java_import 'org.embulk.spi.FormatterPlugin'
  java_import 'org.embulk.spi.ParserPlugin'
  java_import 'org.embulk.spi.InputPlugin'
  java_import 'org.embulk.spi.LineCharacterCodingException'
  java_import 'org.embulk.spi.LineDecoder'
  java_import 'org.embulk.spi.LineDecoderTask'
  java_import 'org.embulk.spi.LineEncoder'
  java_import 'org.embulk.spi.LineEncoderTask'
  java_import 'org.embulk.spi.LineFilterPlugin'
  java_import 'org.embulk.spi.LineGuessPlugin'
  java_import 'org.embulk.spi.OutputPlugin'
  java_import 'org.embulk.spi.ParserPlugin'
  java_import 'org.embulk.spi.PartialTransferException'
  java_import 'org.embulk.spi.PluginThread'
  java_import 'org.embulk.spi.ExecControl'
  java_import 'org.embulk.spi.ExecTask'
  java_import 'org.embulk.spi.ExecConfig'
  java_import 'org.embulk.spi.TextGuessPlugin'
end
