source 'https://rubygems.org/'

# Plugin bundle:
#
# a) Using plugins released on RubyGems:
#   You can write plugin names released on RubyGems here to install them.
#   To use those plugins,
#
#   1. modify this Gemfile. Examples are at the end of this file.
#   2. update Gemfile.lock using: embulk bundle <this dir>
#   3. run embulk with -b option: embulk run -b <this dir> example.yml
#
# b) Using simple single-file ruby plugins:
#
#   You can put a single-file ruby sciprt to <this dir>/embulk directory.
#   When you run embulk with -b <this dir> option, embulk uses them:
#
#   $ embulk run -b <this dir> example.yml
#
#   See <this dir>/embulk/* files for example.
#

# Plugins
#
#gem 'embulk-input-xyz'
#gem 'embulk-output-xyz', '~> 0.1.0'
#gem 'embulk-parser-xyz', '= 0.2.0'
#gem 'embulk-formatter-xyz', '>= 0.3.0'
#

