require 'java'

module QuickLoad
  java_import 'org.quickload.buffer.Buffer'
  java_import 'org.quickload.buffer.BufferAllocator'

  java_import 'org.quickload.channel.BufferChannel'
  java_import 'org.quickload.channel.BufferInput'
  java_import 'org.quickload.channel.BufferOutput'
  java_import 'org.quickload.channel.ChannelAsynchronousCloseException'
  java_import 'org.quickload.channel.ChannelInterruptedException'
  java_import 'org.quickload.channel.DataChannel'
  java_import 'org.quickload.channel.FileBufferChannel'
  java_import 'org.quickload.channel.FileBufferInput'
  java_import 'org.quickload.channel.FileBufferOutput'
  java_import 'org.quickload.channel.PageChannel'
  java_import 'org.quickload.channel.PageInput'
  java_import 'org.quickload.channel.PageOutput'

  #java_import 'org.quickload.config.Config'  # namespace conflicts
  java_import 'org.quickload.config.ConfigDefault'
  java_import 'org.quickload.config.ConfigException'
  java_import 'org.quickload.config.ConfigSource'
  java_import 'org.quickload.config.DataSource'
  java_import 'org.quickload.config.ModelManager'
  java_import 'org.quickload.config.NextConfig'
  java_import 'org.quickload.config.Report'
  java_import 'org.quickload.config.Task'
  java_import 'org.quickload.config.TaskSource'
  java_import 'org.quickload.config.TaskValidationException'

  java_import 'org.quickload.record.Column'
  java_import 'org.quickload.record.ColumnConfig'
  java_import 'org.quickload.record.DoubleType'
  java_import 'org.quickload.record.LongType'
  java_import 'org.quickload.record.Page'
  java_import 'org.quickload.record.PageAllocator'
  java_import 'org.quickload.record.PageReader'
  java_import 'org.quickload.record.Pages'
  java_import 'org.quickload.record.RecordConsumer'
  java_import 'org.quickload.record.RecordCursor'
  java_import 'org.quickload.record.RecordProducer'
  java_import 'org.quickload.record.Schema'
  java_import 'org.quickload.record.SchemaConfig'
  java_import 'org.quickload.record.StringType'
  java_import 'org.quickload.record.Type'
  java_import 'org.quickload.record.TypeManager'

  java_import 'org.quickload.spi.BasicFormatterPlugin'
  java_import 'org.quickload.spi.BasicParserPlugin'
  java_import 'org.quickload.spi.FileDecoderPlugin'
  java_import 'org.quickload.spi.FileEncoderPlugin'
  java_import 'org.quickload.spi.FileInputPlugin'
  java_import 'org.quickload.spi.FileOutputPlugin'
  java_import 'org.quickload.spi.FormatterPlugin'
  java_import 'org.quickload.spi.ParserPlugin'
  java_import 'org.quickload.spi.InputPlugin'
  java_import 'org.quickload.spi.LineCharacterCodingException'
  java_import 'org.quickload.spi.LineDecoder'
  java_import 'org.quickload.spi.LineDecoderTask'
  java_import 'org.quickload.spi.LineEncoder'
  java_import 'org.quickload.spi.LineEncoderTask'
  java_import 'org.quickload.spi.LineFilterPlugin'
  java_import 'org.quickload.spi.OutputPlugin'
  java_import 'org.quickload.spi.ParserGuessPlugin'
  java_import 'org.quickload.spi.ParserPlugin'
  java_import 'org.quickload.spi.PartialTransferException'
  java_import 'org.quickload.spi.PluginThread'
  java_import 'org.quickload.spi.ProcControl'
  java_import 'org.quickload.spi.ProcTask'
  java_import 'org.quickload.spi.ProcTaskSource'
end
